import { LessonContent } from "./lesson1";

export const level0Lesson2: LessonContent = {
  id: "level-0-lesson-2",
  titleEn: "Word Order & Script Practice",
  titleTa: "சொல் வரிசையும் எழுத்துப் பயிற்சியும்",
  levelTitleEn: "Level 0 — Sounds and Script",
  levelTitleTa: "நிலை 0 — ஒலிகளும் எழுத்துக்களும்",
  goalEn: "Practice vowel durations, sentence building with flexible word order, and transliteration.",
  goalTa: "ஒலி கால அளவுகள், நெகிழ்வான சொல் வரிசை வாக்கிய அமைப்பு மற்றும் எழுத்து மாற்றப் பயிற்சி.",
  estMinutes: 12,
  steps: [
    {
      id: "l2-step-1",
      type: "see_it",
      titleEn: "Step 1 of 6 · See It",
      titleTa: "படி 1 / 6 · காண்க",
      content: {
        sanskrit: "रामः वनं गच्छति",
        transliteration: "rāmaḥ vanaṃ gacchati",
        tamilScript: "ராம: வநம் க³ச்ச²தி",
        translationEn: "Rāma goes to the forest.",
        translationTa: "இராமன் காட்டிற்குச் செல்கிறான்.",
        syllables: [
          { text: "रा", iast: "rā", isLong: true },
          { text: "मः", iast: "maḥ", isLong: false },
          { text: "व", iast: "va", isLong: false },
          { text: "नं", iast: "naṃ", isLong: false },
          { text: "ग", iast: "ga", isLong: false },
          { text: "च्छ", iast: "ccha", isLong: false },
          { text: "ति", iast: "ti", isLong: false },
        ],
      },
    },
    {
      id: "l2-step-2",
      type: "notice_it",
      titleEn: "Step 2 of 6 · Notice It",
      titleTa: "படி 2 / 6 · கவனியுங்கள்",
      content: {
        instructionEn: "Tap each word to observe its role in the sentence:",
        instructionTa: "வாக்கியத்தில் ஒவ்வொரு சொல்லின் பங்கைக் கவனிக்க தட்டவும்:",
        tokens: [
          {
            char: "रामः",
            iast: "rāmaḥ",
            tamil: "ராம:",
            nameEn: "The Doer (Kartā)",
            nameTa: "செய்பவர் (கர்தா)",
            detailEn: "The nominative case (prathamā). Marked with visarga (-ḥ).",
            detailTa: "எழுவாய் வேற்றுமை (ப்ரதமா). விஸர்கத்துடன் (-:) முடிகிறது.",
          },
          {
            char: "वनम्",
            iast: "vanam",
            tamil: "வநம்",
            nameEn: "The Destination (Karma)",
            nameTa: "செயப்படுபொருள் (கர்ம)",
            detailEn: "Accusative case (dvitīyā). Marked with anusvāra (-ṃ / -m).",
            detailTa: "இரண்டாம் வேற்றுமை (த்³விதீயா). அடைந்த இடத்தைக் குறிக்கிறது.",
          },
          {
            char: "गच्छति",
            iast: "gacchati",
            tamil: "க³ச்ச²தி",
            nameEn: "The Action (Kriyā)",
            nameTa: "வினைச்சொல் (க்ரியை)",
            detailEn: "Present tense verb: 'goes' (third person singular).",
            detailTa: "நிகழ்கால வினை: 'செல்கிறான் / செல்கிறது'.",
          },
        ],
      },
    },
    {
      id: "l2-step-3",
      type: "rule",
      titleEn: "The Rule: Flexible Word Order",
      titleTa: "விதி: நெகிழ்வான சொல் வரிசை",
      content: {
        headlineEn: "Word Order in Sanskrit (Pada-krama)",
        headlineTa: "சமஸ்கிருத சொல் வரிசை (பத³-க்ரமம்)",
        ruleEn:
          "In Sanskrit, word order is flexible because case endings (vibhakti) explicitly declare the role of each word. Both 'रामः वनं गच्छति' and 'वनं रामः गच्छति' are grammatically valid!",
        ruleTa:
          "சமஸ்கிருதத்தில் சொல் வரிசை மிக நெகிழ்வானது; ஏனெனில் வேற்றுமை உருபுகள் (விபக்தி) ஒவ்வொரு சொல்லின் பங்கையும் தெளிவாக உணர்த்துகின்றன. 'ராம: வநம் கச்சதி' மற்றும் 'வநம் ராம: கச்சதி' இரண்டுமே சரியானவை!",
        bridgeTitleEn: "Tamil & English Connection",
        bridgeTitleTa: "தமிழ் இலக்கண இணைப்பு",
        bridgeTextEn:
          "Unlike English, where 'Rama forest goes' sounds broken, Sanskrit and Tamil allow natural word reordering: 'இராமன் காட்டிற்குச் செல்கிறான்' or 'காட்டிற்கு இராமன் செல்கிறான்' convey the exact same meaning.",
        bridgeTextTa:
          "ஆங்கிலத்தைப் போலன்றி, தமிழிலும் சமஸ்கிருதத்திலும் சொல் வரிசை மாறினாலும் வேற்றுமை உருபுகளால் பொருள் மாறுவதில்லை!",
      },
    },
    {
      id: "l2-step-4",
      type: "exercise",
      titleEn: "Exercise 1 of 4 · Fill the Blank",
      titleTa: "பயிற்சி 1 / 4 · கோடிட்ட இடத்தை நிரப்புக",
      content: {
        id: "ex-l2-1",
        exerciseType: "fill_blank",
        promptEn: "Complete the sentence with the destination (forest):",
        promptTa: "சென்றடையும் இடத்தைக் (காடு) கொண்டு வாக்கியத்தை நிரப்புக:",
        sentenceBefore: "रामः",
        sentenceAfter: "गच्छति ।",
        options: [
          { id: "opt-1", text: "वनम्", helper: "vanam (forest, accusative)" },
          { id: "opt-2", text: "वने", helper: "vane (in forest, locative)" },
          { id: "opt-3", text: "वनात्", helper: "vanāt (from forest, ablative)" },
          { id: "opt-4", text: "वनेन", helper: "vanena (by forest, instrumental)" },
        ],
        correctOptionId: "opt-1",
        explanationEn: "Spot on! 'वनम्' (vanam) carries the -m ending of the accusative destination.",
        explanationTa: "மிகச் சரி! 'வநம்' (vanam) என்பது இரண்டாம் வேற்றுமை அடைவிட உருபாகும்.",
      },
    },
    {
      id: "l2-step-5",
      type: "exercise",
      titleEn: "Exercise 2 of 4 · Match Pairs",
      titleTa: "பயிற்சி 2 / 4 · இணைகளைப் பொருத்துக",
      content: {
        id: "ex-l2-2",
        exerciseType: "match",
        promptEn: "Match each Sanskrit vowel with its mātrā duration:",
        promptTa: "சமஸ்கிருத உயிர் எழுத்துக்களுக்குரிய மாத்திரை கால அளவைப் பொருத்துக:",
        pairs: [
          {
            leftId: "p1-l",
            leftText: "अ",
            leftHelper: "short a",
            rightId: "p1-r",
            rightText: "1 Mātrā (Hrasva)",
            rightHelper: "1 beat",
          },
          {
            leftId: "p2-l",
            leftText: "आ",
            leftHelper: "long ā",
            rightId: "p2-r",
            rightText: "2 Mātrās (Dīrgha)",
            rightHelper: "2 beats",
          },
          {
            leftId: "p3-l",
            leftText: "इ",
            leftHelper: "short i",
            rightId: "p3-r",
            rightText: "1 Mātrā (Hrasva)",
            rightHelper: "1 beat",
          },
          {
            leftId: "p4-l",
            leftText: "ई",
            leftHelper: "long ī",
            rightId: "p4-r",
            rightText: "2 Mātrās (Dīrgha)",
            rightHelper: "2 beats",
          },
        ],
        explanationEn: "Splendid! All short (1 beat) and long (2 beats) vowel pairs matched accurately.",
        explanationTa: "அற்புதம்! குறில் மற்றும் நெடில் மாத்திரை அளவுகளைச் சரியாகப் பொருத்தினீர்கள்.",
      },
    },
    {
      id: "l2-step-6",
      type: "exercise",
      titleEn: "Exercise 3 of 4 · Build the Sentence",
      titleTa: "பயிற்சி 3 / 4 · வாக்கியத்தை அமைக்க",
      content: {
        id: "ex-l2-3",
        exerciseType: "build_sentence",
        promptEn: "Arrange the word tiles to form: 'Rāma goes to the forest'",
        promptTa: "சொல் அட்டைகளை அடுக்கி 'இராமன் காட்டிற்குச் செல்கிறான்' என அமைக்க:",
        promptTranslationEn: "Rāma goes to the forest",
        promptTranslationTa: "இராமன் காட்டிற்குச் செல்கிறான்",
        tiles: [
          { id: "tile-1", text: "रामः", helper: "rāmaḥ (doer)" },
          { id: "tile-2", text: "वनम्", helper: "vanam (forest)" },
          { id: "tile-3", text: "गच्छति", helper: "gacchati (goes)" },
        ],
        acceptedTileSequences: [
          ["tile-1", "tile-2", "tile-3"],
          ["tile-2", "tile-1", "tile-3"],
          ["tile-3", "tile-1", "tile-2"],
        ],
        canonicalSentence: "रामः वनम् गच्छति",
        canonicalSentenceTa: "रामः वनम् गच्छति",
        explanationEn: "Great job! In Sanskrit, both 'रामः वनम् गच्छति' and 'वनम् रामः गच्छति' are fully correct.",
        explanationTa: "அருமை! சமஸ்கிருதத்தில் 'रामः वनम् गच्छति' மற்றும் 'वनम् रामः गच्छति' இரண்டுமே சரியானவை.",
      },
    },
    {
      id: "l2-step-7",
      type: "exercise",
      titleEn: "Exercise 4 of 4 · Transliterate",
      titleTa: "பயிற்சி 4 / 4 · எழுத்து மாற்றுப் பயிற்சி",
      content: {
        id: "ex-l2-4",
        exerciseType: "transliterate",
        promptEn: "Select the correct Roman (IAST) transliteration:",
        promptTa: "சரியான ரோமன் (IAST) ஒலிபெயர்ப்பைத் தேர்ந்தெடுக்கவும்:",
        sourceText: "गच्छति",
        sourceScriptLabel: "Devanāgarī",
        targetScriptLabel: "IAST",
        options: [
          { id: "opt-1", text: "gacchati", helper: "Standard IAST" },
          { id: "opt-2", text: "gachati", helper: "Missing double c" },
          { id: "opt-3", text: "gācchati", helper: "Unwanted long ā" },
          { id: "opt-4", text: "gacchātī", helper: "Unwanted long ī" },
        ],
        correctOptionId: "opt-1",
        explanationEn: "Correct! 'गच्छति' matches 'gacchati' with aspirated 'ch' geminated as 'cch'.",
        explanationTa: "சரி! 'க³ச்ச²தி' என்பது IAST வடிவில் 'gacchati' என எழுதப்படுகிறது.",
      },
    },
    {
      id: "l2-step-8",
      type: "recap",
      titleEn: "Lesson 2 Complete!",
      titleTa: "பாடம் 2 நிறைவுற்றது!",
      content: {
        recapPointsEn: [
          "Mastered fill-the-blank with case endings (-m for destination).",
          "Matched vowel duration pairs (1 beat hrasva vs 2 beat dīrgha).",
          "Discovered flexible word order in Sanskrit sentence building.",
          "Transliterated accurately between Devanāgarī and Roman (IAST).",
        ],
        recapPointsTa: [
          "வேற்றுமை உருபுகளைக் கொண்டு கோடிட்ட இடத்தை நிரப்பப் பழகினீர்கள்.",
          "உயிர் ஒலிகளின் மாத்திரை அளவுகளைப் பொருத்தினீர்கள்.",
          "சமஸ்கிருதத்தின் நெகிழ்வான சொல் வரிசையில் வாக்கியம் அமைத்தீர்கள்.",
          "தேவநாகரி மற்றும் IAST ஒலிபெயர்ப்பை வெற்றிகரமாகச் செய்தீர்கள்.",
        ],
        achievementEn: "You can now build Sanskrit sentences with flexible word order!",
        achievementTa: "நெகிழ்வான சொல் வரிசையுடன் சமஸ்கிருத வாக்கியங்களை நீங்கள் இப்போது உருவாக்க முடியும்!",
      },
    },
  ],
};
