import { LessonContent } from "./lesson1";

export const level1Lesson1: LessonContent = {
  id: "level-1-lesson-1",
  titleEn: "First Sentences & Actions (Subject + Verb)",
  titleTa: "முதல் வாக்கியங்களும் வினைகளும் (எழுவாய் + பயனிலை)",
  levelTitleEn: "Level 1 — First Words and Sentences",
  levelTitleTa: "நிலை 1 — முதல் சொற்களும் வாக்கியங்களும்",
  goalEn: "Understand how Sanskrit connects a singular subject to a present action using the '-ti' ending.",
  goalTa: "சமஸ்கிருதத்தில் ஒருமை எழுவாயுடன் நிகழ்கால வினையை '-தி' (-ti) கொண்டு இணைக்கக் கற்றுக்கொள்ளுங்கள்.",
  estMinutes: 10,
  steps: [
    {
      id: "step-1",
      type: "see_it",
      titleEn: "See It in Action",
      titleTa: "வாக்கிய அமைப்பைக் காணுங்கள்",
      content: {
        sanskrit: "रामः गच्छति  ·  बालकः पठति  ·  गजः चलति",
        tamilScript: "ராமஃ கச்ச2தி  ·  பா3லகஃ பட2தி  ·  க3ஜஃ சலதி",
        transliteration: "rāmaḥ gacchati  ·  bālakaḥ paṭhati  ·  gajaḥ calati",
        syllables: [
          { text: "रा", iast: "rā", tamil: "ரா", isLong: true, durationMs: 400 },
          { text: "मः", iast: "maḥ", tamil: "மஃ", isLong: false, durationMs: 350 },
          { text: "ग", iast: "ga", tamil: "க", isLong: false, durationMs: 300 },
          { text: "च्छ", iast: "ccha", tamil: "ச்ச", isLong: false, durationMs: 300 },
          { text: "ति", iast: "ti", tamil: "தி", isLong: false, durationMs: 300 },
        ],
        translationEn: "Rāma goes. The boy reads. The elephant walks.",
        translationTa: "ராமன் செல்கிறான். சிறுவன் படிக்கிறான். யானை நடக்கிறது.",
      },
    },
    {
      id: "step-2",
      type: "notice_it",
      titleEn: "Notice the Endings",
      titleTa: "சொல் விகுதிகளைக் கவனியுங்கள்",
      content: {
        instructionEn: "Observe the pair: the subject ends with visarga (-ḥ), the action ends with -ti (-ति):",
        instructionTa: "எழுவாய் விஸர்கத்திலும் (-ஃ), வினைச்சொல் -தி (-ति) என்பதிலும் முடிவதைக் கவனிக்கவும்:",
        tokens: [
          {
            sanskrit: "रामः",
            iast: "rāmaḥ",
            tamil: "ராமஃ",
            labelEn: "Subject (Nominative singular masculine)",
            labelTa: "எழுவாய் (ஆண்பால் ஒருமை)",
          },
          {
            sanskrit: "गच्छति",
            iast: "gacchati",
            tamil: "கச்ச2தி",
            labelEn: "Verb (Goes - 3rd person singular)",
            labelTa: "வினை (செல்கிறான் - படர்க்கை ஒருமை)",
          },
        ],
      },
    },
    {
      id: "step-3",
      type: "rule",
      titleEn: "The Agreement Rule",
      titleTa: "இலக்கண விதி",
      content: {
        ruleEn: "In Sanskrit, when one person does an action right now, the verb ends in '-ति' (-ti). Masculine singular names usually end in '-ः' (-ḥ).",
        ruleTa: "ஒருவர் தற்போது ஒரு செயலைச் செய்யும்போது வினைச்சொல் '-தி' (-ti) என்ற விகுதியைப் பெறுகிறது.",
        sutra: "तिप्तस्झि सिप्थस्थ मिब्वस्मस् (Pāṇini 3.4.78)",
        examples: [
          {
            sanskrit: "बालकः पठति",
            iast: "bālakaḥ paṭhati",
            tamil: "பா3லகஃ பட2தி",
            meaningEn: "The boy reads",
            meaningTa: "சிறுவன் படிக்கிறான்",
          },
          {
            sanskrit: "अश्वः धावति",
            iast: "aśvaḥ dhāvati",
            tamil: "அஸ்1வஃ தா4வதி",
            meaningEn: "The horse runs",
            meaningTa: "குதிரை ஓடுகிறது",
          },
        ],
      },
    },
    {
      id: "step-4",
      type: "exercise",
      titleEn: "Choose the Correct Verb",
      titleTa: "சரியான வினைச்சொல்லைத் தேர்ந்தெடுக்கவும்",
      content: {
        exerciseType: "multiple_choice",
        instructionEn: "Complete the sentence: 'The elephant walks' -> 'गजः ______'",
        instructionTa: "வாக்கியத்தை நிரப்பவும்: 'யானை நடக்கிறது' -> 'गजः ______'",
        promptSanskrit: "गजः ______",
        promptHelper: "gajaḥ ______",
        options: [
          { id: "opt-1", text: "चलति", helper: "calati", isCorrect: true },
          { id: "opt-2", text: "पठति", helper: "paṭhati", isCorrect: false },
          { id: "opt-3", text: "पिबति", helper: "pibati", isCorrect: false },
          { id: "opt-4", text: "धावन्ति", helper: "dhāvanti", isCorrect: false },
        ],
        explanationEn: "'चलति' (calati) means 'walks/moves', matching the singular subject 'गजः'.",
        explanationTa: "'चलति' என்றால் 'நடக்கிறது', 'गजः' (யானை) என்பதற்குப் பொருந்தும் சொல்.",
      },
    },
    {
      id: "step-5",
      type: "exercise",
      titleEn: "Build the Sentence",
      titleTa: "வாக்கியத்தை அமைக்கவும்",
      content: {
        exerciseType: "build_sentence",
        instructionEn: "Form the Sanskrit sentence for: 'The boy reads'",
        instructionTa: "'சிறுவன் படிக்கிறான்' என்ற வாக்கியத்தை அமைக்கவும்",
        targetSentence: "बालकः पठति",
        tiles: [
          { id: "t1", text: "बालकः", iast: "bālakaḥ" },
          { id: "t2", text: "पठति", iast: "paṭhati" },
          { id: "t3", text: "गच्छति", iast: "gacchati" },
          { id: "t4", text: "गजः", iast: "gajaḥ" },
        ],
        explanationEn: "'बालकः' (the boy) + 'पठति' (reads).",
        explanationTa: "'बालकः' (சிறுவன்) + 'पठति' (படிக்கிறான்).",
      },
    },
    {
      id: "step-6",
      type: "recap",
      titleEn: "Lesson Recap",
      titleTa: "பாடச் சுருக்கம்",
      content: {
        takeawayEn: "You can now say simple complete thoughts in Sanskrit! Subject (-ḥ) + Verb (-ti).",
        takeawayTa: "இப்போது சமஸ்கிருதத்தில் எளிய முழு வாக்கியங்களை உங்களால் அமைக்க முடிகிறது! எழுவாய் (-ஃ) + வினை (-தி).",
        vocabulary: [
          { sanskrit: "गच्छति", iast: "gacchati", meaningEn: "goes", meaningTa: "செல்கிறான்" },
          { sanskrit: "पठति", iast: "paṭhati", meaningEn: "reads", meaningTa: "படிக்கிறான்" },
          { sanskrit: "चलति", iast: "calati", meaningEn: "walks", meaningTa: "நடக்கிறான்" },
          { sanskrit: "धावति", iast: "dhāvati", meaningEn: "runs", meaningTa: "ஓடுகிறான்" },
        ],
      },
    },
  ],
};

export const level1Lesson2: LessonContent = {
  id: "level-1-lesson-2",
  titleEn: "The Destination & Object (Accusative Case / Dvitīyā)",
  titleTa: "இலக்கும் செயப்படுபொருளும் (இரண்டாம் வேற்றுமை / த்விதீயா)",
  levelTitleEn: "Level 1 — First Words and Sentences",
  levelTitleTa: "நிலை 1 — முதல் சொற்களும் வாக்கியங்களும்",
  goalEn: "Learn how the '-m' / '-am' ending marks where someone is going or what they are reading.",
  goalTa: "செல்லுமிடம் அல்லது செய்யுஞ்செயலை '-ம்' / '-அம்' கொண்டு இரண்டாம் வேற்றுமையில் குறிக்க அறியவும்.",
  estMinutes: 12,
  steps: [
    {
      id: "step-1",
      type: "see_it",
      titleEn: "Reaching the Destination",
      titleTa: "இலக்கை அடைதல்",
      content: {
        sanskrit: "रामः वनं गच्छति  ·  बालकः पुस्तकं पठति",
        tamilScript: "ராமஃ வனம் கச்ச2தி  ·  பா3லகஃ புஸ்தகம் பட2தி",
        transliteration: "rāmaḥ vanaṁ gacchati  ·  bālakaḥ pustakaṁ paṭhati",
        syllables: [
          { text: "रा", iast: "rā", tamil: "ரா", isLong: true, durationMs: 400 },
          { text: "मः", iast: "maḥ", tamil: "மஃ", isLong: false, durationMs: 350 },
          { text: "व", iast: "va", tamil: "வ", isLong: false, durationMs: 300 },
          { text: "नं", iast: "naṁ", tamil: "னம்", isLong: false, durationMs: 350 },
          { text: "ग", iast: "ga", tamil: "க", isLong: false, durationMs: 300 },
          { text: "च्छ", iast: "ccha", tamil: "ச்ச", isLong: false, durationMs: 300 },
          { text: "ति", iast: "ti", tamil: "தி", isLong: false, durationMs: 300 },
        ],
        translationEn: "Rāma goes to the forest. The boy reads the book.",
        translationTa: "ராமன் காட்டிற்குச் செல்கிறான். சிறுவன் புத்தகத்தைப் படிக்கிறான்.",
      },
    },
    {
      id: "step-2",
      type: "notice_it",
      titleEn: "The Magic of '-m' (म् / ं)",
      titleTa: "இரண்டாம் வேற்றுமை உருபு",
      content: {
        instructionEn: "Notice the difference between the base noun and the object:",
        instructionTa: "அடிப்படைச் சொல்லுக்கும் செயப்படுபொருளுக்குமுள்ள வேறுபாட்டைக் கவனியுங்கள்:",
        tokens: [
          {
            sanskrit: "वनम् (वनं)",
            iast: "vanam (vanaṁ)",
            tamil: "வனம்",
            labelEn: "Forest (destination)",
            labelTa: "காடு (இலக்கு)",
          },
          {
            sanskrit: "पुस्तकम् (पुस्तकं)",
            iast: "pustakam (pustakaṁ)",
            tamil: "புஸ்தகம்",
            labelEn: "Book (object being read)",
            labelTa: "புத்தகம் (படிக்கப்படும் பொருள்)",
          },
        ],
      },
    },
    {
      id: "step-3",
      type: "rule",
      titleEn: "The Accusative Case (Dvitīyā Vibhakti)",
      titleTa: "த்விதீயா விபக்தி விதி",
      content: {
        ruleEn: "In Sanskrit, the object of an action or the place of arrival takes the 2nd case (Dvitīyā Vibhakti), marked by '-m' (-म् or anusvāra -ं). Word order is flexible!",
        ruleTa: "ஒரு செயலின் செயப்படுபொருள் அல்லது போய்ச்சேரும் இடம் இரண்டாம் வேற்றுமை உருபான '-ம்' (-म्) பெறுகிறது.",
        sutra: "कर्तुरीप्सिततमं कर्म (Pāṇini 1.4.49)",
        examples: [
          {
            sanskrit: "रामः वनं गच्छति = वनं रामः गच्छति",
            iast: "rāmaḥ vanaṁ gacchati = vanaṁ rāmaḥ gacchati",
            tamil: "ராமஃ வனம் கச்ச2தி",
            meaningEn: "Both mean 'Rāma goes to the forest' because case endings make meaning crystal clear!",
            meaningTa: "வேற்றுமை உருபுகள் தெளிவாக இருப்பதால் சொல் வரிசை மாறினாலும் பொருள் மாறாது!",
          },
        ],
      },
    },
    {
      id: "step-4",
      type: "exercise",
      titleEn: "Fill in the Missing Object",
      titleTa: "விடுபட்ட செயப்படுபொருளை நிரப்பவும்",
      content: {
        exerciseType: "fill_blank",
        instructionEn: "Select the correct form: 'The boy reads the book' -> 'बालकः ______ पठति'",
        instructionTa: "சரியான உருபை தேர்ந்தெடுக்கவும்: 'சிறுவன் புத்தகத்தைப் படிக்கிறான்' -> 'बालकः ______ पठति'",
        sentenceWithBlank: "बालकः ______ पठति",
        options: [
          { id: "opt-1", text: "पुस्तकम्", helper: "pustakam", isCorrect: true },
          { id: "opt-2", text: "पुस्तकः", helper: "pustakaḥ", isCorrect: false },
          { id: "opt-3", text: "पुस्तकेन", helper: "pustakena", isCorrect: false },
        ],
        explanationEn: "'पुस्तकम्' is in the accusative case (object of reading).",
        explanationTa: "'पुस्तकम्' என்பது இரண்டாம் வேற்றுமையில் அமைந்துள்ள சொல்.",
      },
    },
    {
      id: "step-5",
      type: "exercise",
      titleEn: "Assemble the Journey",
      titleTa: "வாக்கியத்தை அடுக்கவும்",
      content: {
        exerciseType: "build_sentence",
        instructionEn: "Build: 'Rāma goes to the forest'",
        instructionTa: "'ராமன் காட்டிற்குச் செல்கிறான்' என்பதை அடுக்கவும்",
        targetSentence: "रामः वनं गच्छति",
        tiles: [
          { id: "t1", text: "रामः", iast: "rāmaḥ" },
          { id: "t2", text: "वनं", iast: "vanaṁ" },
          { id: "t3", text: "गच्छति", iast: "gacchati" },
        ],
        explanationEn: "'रामः' (Subject) + 'वनं' (Destination/Accusative) + 'गच्छति' (Goes).",
        explanationTa: "'रामः' (எழுவாய்) + 'वनं' (இலக்கு) + 'गच्छति' (செல்கிறான்).",
      },
    },
    {
      id: "step-6",
      type: "recap",
      titleEn: "Milestone Achieved!",
      titleTa: "மைல்கல் நிறைவடைந்தது!",
      content: {
        takeawayEn: "You can now understand who does what, and to where! Subject (Nominative) + Object (Accusative) + Verb.",
        takeawayTa: "யார் எதைச் செய்கிறார்கள், எங்குச் செல்கிறார்கள் என்பதை உங்களால் இப்போது முழுமையாக வாசிக்க முடிகிறது!",
        vocabulary: [
          { sanskrit: "वनम्", iast: "vanam", meaningEn: "forest", meaningTa: "காடு" },
          { sanskrit: "पुस्तकम्", iast: "pustakam", meaningEn: "book", meaningTa: "புத்தகம்" },
          { sanskrit: "जलम्", iast: "jalam", meaningEn: "water", meaningTa: "தண்ணீர்" },
        ],
      },
    },
  ],
};
